version: '3'
services:
  postgres:
     image: postgres:11-alpine
     environment:
       - "POSTGRES_USER=test"
       - "POSTGRES_PASSWORD=password"
       - "POSTGRES_DB=rack"
     ports:
       - "5432:5432"
